import test from 'node:test';
import assert from 'node:assert/strict';
import {Game} from '../server/game.js';
import {characters,arena} from '../server/loader.js';
const step=(g,s)=>{for(let t=0;t<s-1e-8;t+=.025)g.tick(Math.min(.025,s-t));};
function setup(t,target='trump',distance=350){const packets=[],g=new Game({emit(){},to:room=>({emit:(name,data)=>packets.push({room,name,data})})},{characters,arena,autoTick:false});t.after(()=>g.dispose());g.join({id:'a'},{character:'biden',team:'A'});g.join({id:'b'},{character:target,team:'B'});g.start();g.countdown=0;const p=g.players.get('a'),q=g.players.get('b');Object.assign(p,{x:150,y:320,fx:1,fy:0,protectT:0,energy:100});Object.assign(q,{x:150+distance,y:320,protectT:0});return {g,p,q,packets};}
function input(g,id,slot){g.input(id,{dx:0,dy:0,[slot]:true});g.tick(.025);g.input(id,{dx:0,dy:0,[slot]:false});}
test('Biden ice cream travels to a target 350 units away and is sent to host and phone',t=>{const {g,q,packets}=setup(t);input(g,'a','attack');assert.equal(q.hp,105);step(g,.4);assert(g.projectiles[0].x>300);g.broadcast();for(const name of ['state','view'])assert(packets.findLast(p=>p.name===name).data.projectiles.some(p=>p.visual==='icecream'));step(g,.6);assert.equal(q.hp,93);});
test('Biden ice cream expires at 400 units and cannot hit beyond range',t=>{const {g,q}=setup(t,'trump',460);input(g,'a','attack');step(g,1.2);assert.equal(q.hp,105);assert.equal(g.projectiles.length,0);});
test('Biden bicycle hits a distant target after travelling, carries it and then releases it',t=>{const {g,p,q,packets}=setup(t,'trump',500);input(g,'a','super');assert.equal(p.energy,0);step(g,.8);assert.equal(q.hp,105);g.broadcast();for(const name of ['state','view'])assert(packets.findLast(p=>p.name===name).data.zones.some(z=>z.kind==='bicycle'));step(g,.7);assert.equal(q.hp,75);step(g,1);assert.equal(q.carriedBy,null);assert(!g.zones.some(z=>z.kind==='bicycle'));});
for(const id of ['trump','obama','macron','musk','biden'])for(const slot of ['attack','super'])test(`Nap blocks ${id} ${slot}, including displacement`,t=>{const {g,p,q}=setup(t,id,60);q.energy=100;input(g,'a','defense');const x=p.x,y=p.y;input(g,'b',slot);g.input('a',{dx:1,dy:0,attack:true,super:true});step(g,1.2);assert.equal(p.hp,105);assert.equal(p.x,x);assert.equal(p.y,y);assert.equal(p.energy,100);assert(p.napT>0);assert(!p.carriedBy);});
test('Nap ends, clears on respawn, and does not allow walking or body pushing',t=>{const {g,p,q,packets}=setup(t,'trump',30);input(g,'a','defense');const x=p.x;g.input('b',{dx:-1,dy:0});step(g,.3);assert.equal(p.x,x);g.broadcast();for(const name of ['state','view'])assert(packets.findLast(p=>p.name===name).data.players.find(p=>p.id==='a').nap>0);g.input('b',{dx:0,dy:0});step(g,2.2);assert(p.napT<=0);assert(g.damage(p,10,'b',q.x,q.y,0));g.spawn(p);assert.equal(p.napT,0);});
